site_name: Developer tourguide
site_description: Developer tour guide test
docs_dir: doc/md/
pages:
  - Home: index.md
  - 'Development of context-aware applications':
      - 'Development of context-aware applications': '01_context/Development of context-aware applications.html'
      - 'Update – query context': '01_context/Update – query context.html'
      - 'Connection to context providers': '01_context/Connection to context providers.html'
      - 'Subscription to context changes': '01_context/Subscription to context changes.html'
      - 'Geolocated context queries': '01_context/Geolocated context queries.html'
  - 'Connection to the Internet of Things':
     - 'Connection to the Internet of Things': '02_iot/Connection to the Internet of Things.md'
     - 'Reading data from IoT devices': '02_iot/Connection to the Internet of Things.md'
     - 'Acting upon IoT devices': '02_iot/Acting upon IoT devices.md'
